package be.ac.ulb.infof307.g04.model;

import java.util.Date;

/**
 * Token that is generated by the server and used for authenticating clients
 *
 */
public class Token {
	/**
	 * Access token used by the client when making requests
	 */
	String access;
	/**
	 * timestamp indicating when the access token expires 
	 */
	Date expires;

	/**
	 * Constructs a Token
	 * @param sequence access token
	 * @param expires expiration date
	 */
	public Token(String sequence,Date expires) {
		this.access = sequence;
		this.expires = expires;
	}
	/**
	 * 
	 * @return the access token
	 */
	public String getAccess() {
		return access;
	}
	/**
	 * Sets the access token
	 * @param access access token
	 */
	public void setAccess(String access) {
		this.access = access;
	}
	
	/**
	 * 
	 * @return the expiration date of the access token
	 */
	public Date getExpires() {
		return expires;
	}
	/**
	 * Sets the expiration date of the access token
	 * @param expires
	 */
	public void setExpires(Date expires) {
		this.expires = expires;
	}
	/**
	 * Check if two tokens refresh are equals
	 * @param tokenToCheck
	 * @return boolean true if equal
	 */
	/**
	 * Check if two tokens acces are equals
	 * @param tokenToCheck
	 * @return boolean true if equal
	 */
	public boolean isAccessEqual(String tokenToCheck) {
		return this.access.equals(tokenToCheck);
	}
}
